In [1]:
from pathlib import Path
import sys
import scanpy as sc
import scipy
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import session_info
import warnings
warnings.filterwarnings('ignore')

In [2]:
plt.rcParams['figure.figsize'] = (4,4)

## Import the draft

In [3]:
base_dir = Path('/home/workspace/private/projects/kim/drg')
panel_dir = base_dir / 'panel/gene-lists/drafts'

input_dir = panel_dir / 'output' # this is where the persist output is
output_dir = panel_dir / 'output'

Path(output_dir).mkdir(parents=True, exist_ok=True)

In [4]:
adata_path = base_dir / 'data/scrna-seq/h5ad/04_clustered/GSE139088-scvi-leiden.h5ad'
bdata_path = base_dir / 'data/scrna-seq/h5ad/04_clustered/GSE254789-nonneurons.h5ad'

draft_path = panel_dir / '2025-07-11_panel-draft_480g.csv'
output_csv = panel_dir / '2025-07-15_panel-480g-formatted-input.csv'

In [5]:
#adata = sc.read_h5ad(adata_path)
#bdata = sc.read_h5ad(bdata_path)

In [6]:
panel = pd.read_csv(draft_path)
panel

,Gene,Ensembl ID,Probesets,zhen_list,spectral_panel,neurons_supervised,neurons_unsupervised,glia_supervised,glia_unsupervised,other,neuron_DEGs,neuron_detection_rate,glia_detection_rate,combined_detection_rate_mean
0,Pdcd1,ENSMUSG00000026285,8.0,True,True,False,False,False,False,False,False,NaN,0.000000,0.000000
1,Adcyap1,ENSMUSG00000024256,8.0,True,False,False,False,False,False,False,False,36.862709,0.889777,18.876243
2,Adra2a,ENSMUSG00000033717,8.0,True,False,False,False,False,False,False,False,4.809395,0.646754,2.728075
3,Asic1,ENSMUSG00000023017,8.0,True,False,False,False,False,False,False,False,12.405630,0.764346,6.584988
4,Asic2,ENSMUSG00000020704,8.0,True,False,False,False,False,False,False,False,72.839966,2.669332,37.754649
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
475,EGFP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
476,tdTomato,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
477,mCherry,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
478,Flp,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
479,Cre,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Format Input column
Specify number of probesets

In [7]:
# Ensure 'Probesets' is numeric and drop NaNs for formatting
panel["Input"] = panel.apply(
    lambda row: f"{row['Gene']},{int(row['Probesets'])}" if pd.notna(row['Probesets']) else None,
    axis=1
)

In [9]:
panel

,Gene,Ensembl ID,Probesets,zhen_list,spectral_panel,neurons_supervised,neurons_unsupervised,glia_supervised,glia_unsupervised,other,neuron_DEGs,neuron_detection_rate,glia_detection_rate,combined_detection_rate_mean,Input
0,Pdcd1,ENSMUSG00000026285,8.0,True,True,False,False,False,False,False,False,NaN,0.000000,0.000000,"Pdcd1,8"
1,Adcyap1,ENSMUSG00000024256,8.0,True,False,False,False,False,False,False,False,36.862709,0.889777,18.876243,"Adcyap1,8"
2,Adra2a,ENSMUSG00000033717,8.0,True,False,False,False,False,False,False,False,4.809395,0.646754,2.728075,"Adra2a,8"
3,Asic1,ENSMUSG00000023017,8.0,True,False,False,False,False,False,False,False,12.405630,0.764346,6.584988,"Asic1,8"
4,Asic2,ENSMUSG00000020704,8.0,True,False,False,False,False,False,False,False,72.839966,2.669332,37.754649,"Asic2,8"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
475,EGFP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
476,tdTomato,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
477,mCherry,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
478,Flp,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
479,Cre,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None

In [8]:
panel.to_csv(output_csv, index = False)